version: '3'
services:
  nginx:
    image: "nginx:stable-alpine"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html
    environment:
      VIRTUAL_HOST: "controlinmobiliario.cl"
      LETSENCRYPT_HOST: "controlinmobiliario.cl"
      LETSENCRYPT_EMAIL: "cristopher@wetrust.cl"
    networks:
      - wetrust
networks:
  wetrust:
    external: true
